version: "2"
services:


  elixir-node-4000:
    build: .
    image: elixir-node
    hostname: elixir-node-4000
    environment:
      PORT: 4000
      PERSISTENCE_PATH: /elixir_node/aecore/priv/rox_db_4000
    volumes:
      - elixir-node-4000-db:/elixir_node/apps/aecore/priv/rox_db_4000
    command: -e "Aecore.Miner.Worker.resume()"


  elixir-node-4001:
      build: .
      image: elixir-node
      hostname: elixir-node-4001
      environment:
        SYNC_PORT: 3017
        PORT: 4001
        PERSISTENCE_PATH: /elixir_node/aecore/priv/rox_db_4001
      volumes:
        - elixir-node-4001-db:/elixir_node/apps/aecore/priv/rox_db_4001
      stdin_open: true
      tty: true
      command: -e "pubkey = Aehttpclient.Client.get_info(\"elixir-node-4000:4000\") |> elem(1) |> Map.get(:public_key)" -e "decoded_pubkey = Aecore.Account.Account.base58c_decode(pubkey)" -e "peer = Map.put(%{}, :host, 'elixir-node-4000') |> Map.put(:port, 3015) |> Map.put(:pubkey, decoded_pubkey)" -e "Aecore.Peers.Worker.try_connect(peer)" -e "Aecore.Miner.Worker.resume()"


  elixir-node-4002:
      build: .
      image: elixir-node
      hostname: elixir-node-4002
      environment:
        SYNC_PORT: 3016
        PORT: 4002
        PERSISTENCE_PATH: /elixir_node/aecore/priv/rox_db_4002
      volumes:
        - elixir-node-4002-db:/elixir_node/apps/aecore/priv/rox_db_4002
      command: -e "pubkey = Aehttpclient.Client.get_info(\"elixir-node-4000:4000\") |> elem(1) |> Map.get(:public_key)" -e "decoded_pubkey = Aecore.Account.Account.base58c_decode(pubkey)" -e "peer = Map.put(%{}, :host, 'elixir-node-4000') |> Map.put(:port, 3015) |> Map.put(:pubkey, decoded_pubkey)" -e "Aecore.Peers.Worker.try_connect(peer)"


  proxy:
    image: nginx:1.13.8
    hostname: proxy
    ports:
     - "4000:4000"
     - "4001:4001"
     - "4002:4002"
    volumes:
      - ${PWD}/docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/docker/nginx-cors.conf:/etc/nginx/cors.conf


volumes:
  elixir-node-4000-db:
  elixir-node-4001-db:
  elixir-node-4002-db:
